import { StyleSheet } from "react-native";
import { COLORS } from "../constants/chatConstants";

export const styles = StyleSheet.create({
  container: { flex: 1 },

  topBar: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  hamburgerBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  centerTitle: { flex: 1, alignItems: "center", justifyContent: "center" },
  rightSpacer: { width: 44 },

  titleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  botAvatar: {
    width: 28,
    height: 28,
    borderRadius: 12,
    backgroundColor: "rgba(255,177,90,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,177,90,0.28)",
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    color: COLORS.text,
    fontWeight: "900",
    fontSize: 16,
    letterSpacing: 0.2,
  },

  chat: { flex: 1 },
  chatContent: { paddingHorizontal: 16, paddingTop: 8 },

  bubbleRow: { marginBottom: 10, flexDirection: "row" },
  bubbleRowAI: { justifyContent: "flex-start" },
  bubbleRowUser: { justifyContent: "flex-end" },

  bubble: {
    maxWidth: "80%",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
  },
  bubbleAI: {
    backgroundColor: COLORS.bubbleAI,
    borderColor: COLORS.bubbleAIBorder,
    borderTopLeftRadius: 10,
  },
  bubbleUser: {
    backgroundColor: COLORS.bubbleUser,
    borderColor: "rgba(0,0,0,0.12)",
    borderTopRightRadius: 10,
  },
  bubbleText: { fontSize: 13, fontWeight: "800", lineHeight: 18 },
  bubbleTextAI: { color: COLORS.text },
  bubbleTextUser: { color: "#0B1220" },

  inputArea: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: 0,
  },
  inputBar: {
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.inputBg,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    borderRadius: 18,
    paddingHorizontal: 10,
    gap: 10,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    flex: 1,
    color: COLORS.text,
    fontWeight: "800",
    fontSize: 13,
    paddingVertical: 0,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: COLORS.orange,
    alignItems: "center",
    justifyContent: "center",
  },

  overlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.25)",
  },

  drawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: COLORS.drawerBg,
    borderRightWidth: 1,
    borderRightColor: COLORS.drawerBorder,
    paddingHorizontal: 14,
  },
  drawerHeader: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  drawerTitle: { color: COLORS.text, fontWeight: "900", fontSize: 14 },
  drawerDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginBottom: 10,
  },

  chatItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    marginBottom: 10,
  },
  chatItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: "rgba(255,177,90,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,177,90,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  chatItemTitle: { color: COLORS.text, fontWeight: "900", fontSize: 12 },
  chatItemMeta: {
    color: "rgba(234,244,255,0.55)",
    fontWeight: "800",
    fontSize: 11,
    marginTop: 3,
  },

  newChatBtn: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: COLORS.orange,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.15)",
    marginTop: 6,
  },
  newChatText: { color: "#0B1220", fontWeight: "900", fontSize: 12 },
});
