import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { padding: 16, paddingBottom: 28 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 30, height: 30 },
  brandText: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: COLORS.danger,
    width: 18,
    height: 18,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.bg,
  },
  notificationBadgeText: {
    color: "#FFF",
    fontSize: 9,
    fontWeight: "900",
  },

  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "700",
    paddingVertical: 0,
  },
  searchGo: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "rgba(123,190,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(123,190,255,0.25)",
  },
  searchGoText: { color: COLORS.text, fontWeight: "900", fontSize: 12 },

  vetCard: {
    position: "relative",
    overflow: "hidden",
    flexDirection: "row",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: COLORS.card2,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 12,
  },
  vetBgWrap: {
    position: "absolute",
    inset: 0,
    opacity: 0.35,
  },
  vetBgImg: { width: "100%", height: "100%" },

  vetTitle: { color: COLORS.text, fontSize: 16, fontWeight: "900" },
  vetDesc: {
    color: COLORS.muted,
    marginTop: 6,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  vetActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    flexWrap: "wrap",
  },
  vetPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: COLORS.warm,
  },
  vetPrimaryText: { color: "#0B1220", fontWeight: "900", fontSize: 12 },
  vetSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  vetSecondaryText: { color: COLORS.text, fontWeight: "900", fontSize: 12 },
  vetIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "rgba(255,170,90,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,170,90,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },

  rowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    marginTop: 2,
  },
  sectionTitle: { color: COLORS.text, fontSize: 14, fontWeight: "900" },
  link: { color: "rgba(123,190,255,0.9)", fontWeight: "900", fontSize: 12 },

  chipsList: { paddingBottom: 12, gap: 10 },

  herdChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 88,
    minWidth: 170,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
  },
  herdChipLeft: {
    justifyContent: "center",
  },
  herdChipBgImg: {
    width: 64,
    height: 64,
    opacity: 0.55,
  },
  herdChipValue: {
    color: COLORS.text,
    fontWeight: "900",
    fontSize: 20,
    lineHeight: 22,
  },
  herdChipLabel: {
    color: COLORS.muted,
    fontWeight: "800",
    fontSize: 13,
    marginTop: 4,
  },

  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 12 },
  quickCard: {
    width: "48%",
    padding: 14,
    borderRadius: 18,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    position: "relative",
    overflow: "hidden",
  },
  quickCardGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  quickIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  quickIconInner: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  quickTitle: {
    color: COLORS.text,
    fontWeight: "900",
    fontSize: 14,
    marginBottom: 4,
  },
  quickSub: {
    color: COLORS.muted,
    fontWeight: "700",
    fontSize: 11,
    lineHeight: 14,
  },
  quickCardCorner: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 20,
    height: 20,
    borderTopRightRadius: 8,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.08)",
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },

  // DONUT CHART
  healthCard: {
    backgroundColor: COLORS.card2,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 16,
    marginTop: 10,
  },
  healthHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  healthTitle: { color: COLORS.text, fontWeight: "900", fontSize: 15 },
  healthSubtitle: {
    color: COLORS.muted,
    fontWeight: "700",
    fontSize: 11,
    marginTop: 3,
  },

  donutContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
  },
  donutChartWrapper: {
    alignItems: "center",
    justifyContent: "center",
  },

  donutLegend: {
    flex: 1,
    gap: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
  },
  legendInfo: {
    flex: 1,
  },
  legendLabel: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 2,
  },
  legendValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  legendValue: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "900",
  },
  legendPercentage: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "700",
  },

  activitiesCard: {
    backgroundColor: COLORS.card2,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 14,
    marginTop: 10,
  },
  activitiesHeader: { marginBottom: 8 },
  activitiesTitle: { color: COLORS.text, fontWeight: "900", fontSize: 14 },

  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
  },
  activityIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activityTitle: { color: COLORS.text, fontWeight: "900", fontSize: 12 },
  activityMeta: {
    color: COLORS.muted,
    fontWeight: "700",
    fontSize: 11,
    marginTop: 3,
  },

  moreBtn: {
    marginTop: 10,
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(123,190,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(123,190,255,0.18)",
  },
  moreBtnText: { color: COLORS.text, fontWeight: "900", fontSize: 12 },
});
